### ISSUE TITLE
Errors on 2021.4.0

### ISSUE THREAD

**Issue by KapJI** [leikoilja/ha-google-home#165]
## Describe the bug

I see multiple errors in logs and sensors are not created. Don't have much time to investigate further right now.

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.3.0
```

## Glocaltokens Version (Underlying package)

```text
0.3.0
```

## Logs

```text
Logger: glocaltokens.client
Source: /home/ruslan/homeassistant_venv/lib/python3.9/site-packages/glocaltokens/client.py:325
First occurred: 11:28:58 AM (1 occurrences)
Last logged: 11:28:58 AM

[GRPC] Received unknown RPC error: code=StatusCode.INTERNAL message=Internal error encountered.
```

```text
Logger: custom_components.google_home
Source: custom_components/google_home/api.py:82
Integration: Google Home (documentation, issues)
First occurred: 11:29:18 AM (1 occurrences)
Last logged: 11:29:18 AM

Unexpected error fetching sensor data: 'NoneType' object has no attribute 'home'
Traceback (most recent call last):
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 143, in _async_update_data
    return await self.update_method()
  File "/home/ruslan/.homeassistant/custom_components/google_home/api.py", line 206, in update_google_devices_information
    devices = await self.get_google_devices()
  File "/home/ruslan/.homeassistant/custom_components/google_home/api.py", line 87, in get_google_devices
    google_devices = await self.hass.async_add_executor_job(_get_google_devices)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ruslan/.homeassistant/custom_components/google_home/api.py", line 82, in _get_google_devices
    return self._client.get_google_devices(
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/glocaltokens/client.py", line 379, in get_google_devices
    LOGGER.debug("Iterating in %d homegraph devices", len(homegraph.home.devices))
AttributeError: 'NoneType' object has no attribute 'home'
```

This one is when updating options:
```text
Logger: aiohttp.server
Source: custom_components/google_home/config_flow.py:118
First occurred: 11:31:04 AM (1 occurrences)
Last logged: 11:31:04 AM

Error handling request
Traceback (most recent call last):
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 172, in forwarded_middleware
    return await handler(request)
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 129, in auth_middleware
    return await handler(request)
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 213, in post
    return await super().post(request, flow_id)
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 107, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 156, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/home/ruslan/homeassistant_venv/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 214, in _async_handle_step
    result: dict = await getattr(flow, method)(user_input)
  File "/home/ruslan/.homeassistant/custom_components/google_home/config_flow.py", line 118, in async_step_user
    self.options.update(user_input)
AttributeError: 'mappingproxy' object has no attribute 'update'
```

**Comment by DurgNomis-drol** [comment]
Same here, tried reinstalling and the problem persist. I have an 2021.3.4 instance running. I will test if the problems also occurs on that. 😄

**Comment by DurgNomis-drol** [comment]
I found these two breaking changes, they may, or may not be related. [1](https://github.com/home-assistant/core/pull/48387) and [2](https://github.com/home-assistant/core/pull/48302)

**Comment by DurgNomis-drol** [comment]
I just tried installing 1.2 and it fails at the same point, though I don't have same details in log as 1.3 😢

**Comment by KapJI** [comment]
This means that's not something we broke in 1.3 😀
Btw, releasing them in the same day was not the greatest idea.

**Comment by DurgNomis-drol** [comment]
I though the exact same thing moments ago. 😆

**Comment by KapJI** [comment]
After downgrading to 2021.3.4 it works again on 1.3.0. So yeah, something is wrong with the new version.

**Comment by KapJI** [comment]
Also it works after upgrading back to 2021.4.0. So initial setup is actually broken.

**Comment by KapJI** [comment]
I can no longer reproduce this. Looking at the error again:
```
[GRPC] Received unknown RPC error: code=StatusCode.INTERNAL message=Internal error encountered.
```

It might be there was an issue with Foyer API itself.

**Comment by DurgNomis-drol** [comment]
Nice find! But why does this only happen on the newer version. I haven't got that error, so i can either reproduce it. 

It would be a hell of a coincidence if that was the case. Just looked up to see if there have been any reported problems with Google Home, and cannot find any.

Is `grpcio` and `grpcio-tools` still pinned on 2021.4? 

But i got a say that error message is about as useful as just saying error. 🤣

**Comment by DurgNomis-drol** [comment]
> This PR pins (and thus downgrades) the gRPC Python package grpcio from latest release (1.32.0) to the 1.31.0 release.
Main reason for this, is the issue it causes on the armv7 platforms using our containers (and thus wheels).
It seems like it want to use a backtrace, however, that is not available in musl based systems (like Alpine).
While not a solution, we do have working wheels for 1.31.0, and can make multiple integration working again.

home-assistant/core#40678 

I unfortunately don't think it is possible right now.

**Comment by KapJI** [comment]
Well, they had issues with 1.32, the latest is 1.37. There is a chance, it was that issue was already fixed.

**Comment by DurgNomis-drol** [comment]
I will test with latest. give me a moment to see if it work.

**Comment by KapJI** [comment]
You also need to test 1.32 to make sure you can reproduce this issue there. Ideally, it's nice to test all versions between 1.32 and 1.37 to have stronger supporting data.

**Comment by DurgNomis-drol** [comment]
Yes, something strange just happened. I just installed `grpcio` and `grpcio-tools` with out it having to build the wheels. With other version i always had build them from scratch.

I will first test if the new version actually fixes our problems and then go back and test the other packages in a more controlled environment so we can get some clean data about which versions works and fails.

**Comment by KapJI** [comment]
This is how it should work, they ship wheels for all platforms: https://pypi.org/project/grpcio/#files

**Comment by KapJI** [comment]
Well, honestly I don't think our issues are caused by this. But it'd be nice to help HA community and unpin grpcio if possible. For us it will be just faster and simpler installation with initial `poetry install`.

**Comment by DurgNomis-drol** [comment]
But they didn't do that before. When me and @leikoilja first started out we had to build the wheels when we installed it, until we pinned our version as the same HA and add `grpcio-tools` to to [custom wheels](https://github.com/home-assistant/wheels-custom-integrations)

**Comment by KapJI** [comment]
Yeah, I also was building it, not sure why older versions are not using precompiled wheels.

**Comment by KapJI** [comment]
Oh, I know. Older ones were only built for Python 3.8 and I use 3.9.
- Since 1.33.1 they provide wheels for 3.9 as well. 
- And they just started to provide wheels for arm64 in 1.37.0, so it might be fixed there.

**Comment by DurgNomis-drol** [comment]
I just tried installing version 1.3 of google home and now it works for me. 🤔 This is really strange. I will investigate some more about `grpcio` and `grpcio-tools`. But lets move that to another issue. 😄

**Comment by DurgNomis-drol** [comment]
With grpcio 1.31, testing now with 1.37

**Comment by DurgNomis-drol** [comment]
Running 1.37 now and it seems to work. I cannot not remove the integration and add it again, because HA will then automatically downgrade. But it seems that we can relax our requirements. Maybe doing a test release of glocaltokens so we can test it?

**Comment by KapJI** [comment]
We can't use newer version of grpc if it's still pinned in HA, that's the point of unpinning it 🙂

**Comment by DurgNomis-drol** [comment]
Shouldn't we be able to force our own version when glocaltokens is installed. And yes we should aim to get it unpinned. Me and @leikoilja was able to do that in the beginning before we pinned glocaltokens version to the same as HA.

**Comment by DurgNomis-drol** [comment]
I now got this error:

```text
2021-04-09 00:05:58 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 573, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 485, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/google_home/__init__.py", line 19, in <module>
    from .api import GlocaltokensApiClient
  File "/config/custom_components/google_home/api.py", line 9, in <module>
    from glocaltokens.client import Device, GLocalAuthenticationTokens
  File "/usr/local/lib/python3.8/site-packages/glocaltokens/client.py", line 10, in <module>
    import grpc
  File "/usr/local/lib/python3.8/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /usr/local/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-arm-linux-gnueabihf.so)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 120, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 580, in async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
```

This occurs after a restart. I am running 1.37

**Comment by KapJI** [comment]
I think HA should prioritise its package constraints over component manifest. But even if it's possible, it can break other components if that issue on arm devices is not fixed.

**Comment by DurgNomis-drol** [comment]
I know and I agree. 😄 But I am not 100% sure (other then the one you linked further up) what other integrations/components is affected. I am not 100% sure how we can prove that they can safely unpin it, but maybe you have some knowledge about that?

**Comment by KapJI** [comment]
Yes. `from grpc._cython import cygrpc as _cygrpc` shouldn't fail 😀

**Comment by DurgNomis-drol** [comment]
I am not sure i understand what you mean by that 🤔

**Comment by KapJI** [comment]
The reason why they pinned it was that import failing on raspberry pi with grpcio 1.32. If it no longer fails with newer version, it can be unpinned.

**Comment by DurgNomis-drol** [comment]
What is the best way to test this? can we just execute a script inside the HA container (or other alpine container on RPI) and see if it fails?

**Comment by KapJI** [comment]
Yeah, should be enough.

**Comment by DurgNomis-drol** [comment]
Right this should be trivial to test then. Give me a sec.

Another thing, I have experienced that the integration simply fails after some time. with out any real reason. But i hope 1.3 fixes this. Will report back about it tomorrow. 😄

**Comment by DurgNomis-drol** [comment]
It still fails with 1.37 😢

**Comment by DurgNomis-drol** [comment]
Maybe you have the skill to look into `grpcio` and `grpcio-tools` and fix it? 🤞

**Comment by KapJI** [comment]
This looks promising: https://github.com/grpc/grpc/issues/24002#issuecomment-814022836

**Comment by DurgNomis-drol** [comment]
Unfortunately ARM64 is not compatible with ARMv7 😢

**Comment by KapJI** [comment]
After update to 2021.4.1 I have the same issues again. I collected logs, will see what's going on there.

**Comment by DurgNomis-drol** [comment]
I just updated to 2021.4.1 and it works for me.

**Comment by leikoilja** [comment]
Just installed 2021.4.1 and works fine for me 🤔  Could there be some issues with some other packages or dependancies some might have as we had with LG components? 🤔  @KapJI do you have any custom components/integrations enabled? :)

**Comment by DurgNomis-drol** [comment]
@KapJI What do we think about this issue now? Do we think it is related to the one we just fixed or?

**Comment by KapJI** [comment]
I think it fixed the issue I had but still indicates about that some errors are not handled properly. They are mostly on `glocaltokens` side but options are on integration side.

**Comment by DurgNomis-drol** [comment]
Should we split them up to keep track of the separately?
