### ISSUE TITLE
Integration doesn't load

### ISSUE THREAD

**Issue by CoryAlbrecht** [leikoilja/ha-google-home#290]
## Describe the bug

Integration doesn't load

## Version of the integration

1.50

## Logs

```text
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/google_home/api.py:10
Integration: Google Home (documentation, issues)
First occurred: 14:47:51 (1 occurrences)
Last logged: 14:47:51

Setup failed for google_home: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 201, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/google_home/__init__.py", line 19, in <module>
    from .api import GlocaltokensApiClient
  File "/config/custom_components/google_home/api.py", line 10, in <module>
    from glocaltokens.client import Device, GLocalAuthenticationTokens
  File "/usr/local/lib/python3.9/site-packages/glocaltokens/client.py", line 23, in <module>
    from .google.internal.home.foyer.v1_pb2 import GetHomeGraphRequest, GetHomeGraphResponse
  File "/usr/local/lib/python3.9/site-packages/glocaltokens/google/internal/home/foyer/v1_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

**Comment by CoryAlbrecht** [comment]
Home Assistant version 2021.7.0

**Comment by CoryAlbrecht** [comment]
This also prevents me from deleting the integration from Home Assistant.

**Comment by CoryAlbrecht** [comment]
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/google_home/api.py:10
Integration: Google Home (documentation, issues)
First occurred: 15:32:56 (8 occurrences)
Last logged: 15:32:56

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 696, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/google_home/__init__.py", line 19, in <module>
    from .api import GlocaltokensApiClient
  File "/config/custom_components/google_home/api.py", line 10, in <module>
    from glocaltokens.client import Device, GLocalAuthenticationTokens
  File "/usr/local/lib/python3.9/site-packages/glocaltokens/client.py", line 23, in <module>
    from .google.internal.home.foyer.v1_pb2 import GetHomeGraphRequest, GetHomeGraphResponse
  File "/usr/local/lib/python3.9/site-packages/glocaltokens/google/internal/home/foyer/v1_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

**Comment by DurgNomis-drol** [comment]
Currently the integration does not work with 2021.7. As of now see #288 for more info.

**Comment by Raul-7-7** [comment]
@DurgNomis-drol what do you mean it doesnt work with 2021.7? I am on 2021.7.3 and it works fine.

**Comment by DurgNomis-drol** [comment]
@Raul-7-7 thought it didn't work on 2021.7 because glocaltokens won't install, but i am glad to hear i am wrong 😂 But maybe that is an issue which is related to the switch in alpine base images instead.

**Comment by Raul-7-7** [comment]
@DurgNomis-drol It is working here, however I just want to clarify, I installed it back when it was released, so not sure which version of HA i did my initial installation on, but it has continued to work through upgrading HA.

**Comment by ArnyminerZ** [comment]
Maybe the issue comes when first installing the integration on a clean 2021.7 installation, and if it was installed before doesn't cause any issues. This should be discussed and followed at #288 as @DurgNomis-drol has stated.

**Comment by CoryAlbrecht** [comment]
@ArnyminerZ I had the extension installed previously to 2021.7 and am having the issue, rather than a new install on 2021.7, which would seem to disprove your hypothesis. :-(

**Comment by DurgNomis-drol** [comment]
@CoryAlbrecht Can you try to update to 2021.7.4 and then reinstall the integration? 😃

**Comment by CoryAlbrecht** [comment]
@DurgNomis-drol I just updated, but I still l cannot delete it via the UI. Is deleting `…/config/custom_components/google_home` 
 and restarting HA sufficient to remove it?

**Comment by DurgNomis-drol** [comment]
You should remove it in the UI first, then delete this `…/config/custom_components/google_home`. Then restart. If it still is in the UI then delete it there again, it will probably throw an error but that is fine. And the restart again.

And then you can try reinstalling it.

**Comment by CoryAlbrecht** [comment]
```
Error
Config flow could not be loaded
```

**Comment by DurgNomis-drol** [comment]
Yep, that is the error. Which is expected as you don't have it installed any more. Try reinstalling it.

**Comment by CoryAlbrecht** [comment]
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/google_home/api.py:10
Integration: Google Home (documentation, issues)
First occurred: 17:53:01 (9 occurrences)
Last logged: 18:00:04

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 696, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/google_home/__init__.py", line 19, in <module>
    from .api import GlocaltokensApiClient
  File "/config/custom_components/google_home/api.py", line 10, in <module>
    from glocaltokens.client import Device, GLocalAuthenticationTokens
  File "/usr/local/lib/python3.9/site-packages/glocaltokens/client.py", line 23, in <module>
    from .google.internal.home.foyer.v1_pb2 import GetHomeGraphRequest, GetHomeGraphResponse
  File "/usr/local/lib/python3.9/site-packages/glocaltokens/google/internal/home/foyer/v1_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

**Comment by CoryAlbrecht** [comment]
@DurgNomis-drol That was after reinstalling.

**Comment by CoryAlbrecht** [comment]
```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/google_home/api.py:10
Integration: Google Home (documentation, issues)
First occurred: 17:55:58 (1 occurrences)
Last logged: 17:55:58

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 696, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/google_home/__init__.py", line 19, in <module>
    from .api import GlocaltokensApiClient
  File "/config/custom_components/google_home/api.py", line 10, in <module>
    from glocaltokens.client import Device, GLocalAuthenticationTokens
  File "/usr/local/lib/python3.9/site-packages/glocaltokens/client.py", line 23, in <module>
    from .google.internal.home.foyer.v1_pb2 import GetHomeGraphRequest, GetHomeGraphResponse
  File "/usr/local/lib/python3.9/site-packages/glocaltokens/google/internal/home/foyer/v1_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

**Comment by DurgNomis-drol** [comment]
What system are your running Home Assistant on? What installation method have you used?

This is a strange issue, that i am not sure why is happening. We need as much information about your setup as possible, this will make it easier to understand why.

**Comment by CoryAlbrecht** [comment]
Home Assistant supervised from https://github.com/home-assistant/supervised-installer in a Linux VM.

**Comment by DurgNomis-drol** [comment]
@CoryAlbrecht What operating system?

**Comment by CoryAlbrecht** [comment]
Ubuntu 20.04 LTS.

**Comment by DurgNomis-drol** [comment]
It seems that maybe something went wrong when installing glocaltokens. Have you tried installing it manually on cmdline again?

**Comment by CoryAlbrecht** [comment]
Yes, I have tried that that several times.

**Comment by CoryAlbrecht** [comment]
Any other ideas?

**Comment by leikoilja** [comment]
hmmm, except dedicating a separate space for HomeAssistant like HomeAssistant OS, not really :/ I guess that's the major reason for using their OS - you eliminate the need to worry about installing all the dependencies. I am currently running my HA instance on RPi with their OS but was considering to move to a generic linux distribution and having HA in a container side by side with some of my other projects. I ll keep you in the loop I if get my hands on that, because I will probably need to go through the same process as you, @CoryAlbrecht, of installing `supervised` on top of my debian distro 🤔 😅

**Comment by DurgNomis-drol** [comment]
Running Home Assistant OS or running Home Assistant Container, should have the same compatibility. As Home Assistant OS is just Home Assistant Container + some other things (Like superviser and addon store). The only thing that can be problem is what architecture you are running on. Be aware that there are differences in older ARM architectures (32 bit) and arm64.

**Comment by CoryAlbrecht** [comment]
I assume there's a python equivalent for ldd? (I'm a perl hacker, don;t know python.) Could you use that hypothetical `py-ldd` on working system, tell me how to do it, too, and I can compare?

**Comment by KapJI** [comment]
Probably you have some incompatible version of protobuf. `_internal_create_key` is there for quite a long time:
https://github.com/protocolbuffers/protobuf/blame/master/python/google/protobuf/descriptor.py#L111

In venv: `pip freeze | grep protobuf`. My installation has version 3.15.6.

**Comment by CoryAlbrecht** [comment]
In the VM

```
root@ha:~# pip freeze | grep protobuf
protobuf==3.17.3
```

**Comment by KapJI** [comment]
Version 3.17.3 should have `_internal_create_key`: https://github.com/protocolbuffers/protobuf/blob/v3.17.3/python/google/protobuf/descriptor.py#L111

Something is wrong with your installation, try to reinstall it. Or open an issue for protobuf.

**Comment by CoryAlbrecht** [comment]
If I create a new VM and download a backup (I use the Google Drive backup addon) of my current one, will that just recreate the problem? I'm not really too keen on reinstalling and building up my system from scratch,

**Comment by KapJI** [comment]
Yes, if HA is installed on the VM, that should be enough.

**Comment by CoryAlbrecht** [comment]
I created a brand new VM and restored a HA backup, but restoring the backup also restored the issue. :-(

**Comment by CoryAlbrecht** [comment]
So I spent the day duplicating a base image of a Debian 11 VM, installing HA repeatedly and restoring various levels of partial backups, installing this integration before doing the restore, and everything I could think of to bring over all my input_booleans, input_texts, and so on that I made with the HA UI (which I am loathe to lose because there are so many of them, but nothing works. :-(

Any other suggestions of things to try?

**Comment by KapJI** [comment]
Do you have access to python venv where HA is running? I wonder if you can do such test:

In python shell:
```python
>>> from google.protobuf import descriptor
>>> descriptor.__file__
'/home/user/homeassistant_venv/lib/python3.9/site-packages/google/protobuf/descriptor.py'
```

And then compare contents of that file to what it should be: https://github.com/protocolbuffers/protobuf/blob/v3.17.3/python/google/protobuf/descriptor.py

Especially check the presence of `_internal_create_key`.

Anothing thing you can try is just to use some official HA container where it should be setup correctly.

**Comment by CoryAlbrecht** [comment]
@KapJI 
```
root@ha:~# docker container exec -it homeassistant bash
bash-5.1# python
python                                        python-argcomplete-tcsh                       python3                                       python3.9                                     
python-argcomplete-check-easy-install-script  python-config                                 python3-config                                python3.9-config                              
bash-5.1# python
Python 3.9.6 (default, Jul  6 2021, 16:49:41) 
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import descriptor
>>> descriptor.__file__
'/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py'
>>> descriptor._internal_create_key
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
>>> 
```

**Comment by CoryAlbrecht** [comment]
@KapJI 
> Anothing thing you can try is just to use some official HA container where it should be setup correctly.

Like I said previously, I have a lot of helper entities which were made via the UI so I can't "just use" something else as that would mean losing all of that. That's why I tried getting this integration to work in a test VM and then restoring a backup of my "production" HA to retain all that.

**Comment by KapJI** [comment]
So what's inside of this file? `/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py`

Protobuf has `_internal_create_key` there for quite a long time, why it's not there on your system?

**Comment by CoryAlbrecht** [comment]
```
root@ha:~# docker container exec -it homeassistant bash
bash-5.1# vi /usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py
bash-5.1# python
Python 3.9.6 (default, Jul  6 2021, 16:49:41) 
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import descriptor
>>> descriptor.__file__
'/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py'
>>> descriptor._internal_create_key
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
>>> quit()
bash-5.1# pip3 install protobuf
Requirement already satisfied: protobuf in /usr/local/lib/python3.9/site-packages (3.6.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from protobuf) (57.1.0)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.9/site-packages (from protobuf) (1.16.0)
WARNING: You are using pip version 20.2.4; however, version 21.2.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
bash-5.1# pip3 install --force-reinstall protobuf
Collecting protobuf
  Using cached protobuf-3.17.3-py2.py3-none-any.whl (173 kB)
Collecting six>=1.9
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, protobuf
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.6.1
    Uninstalling protobuf-3.6.1:
      Successfully uninstalled protobuf-3.6.1
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

pyicloud 0.10.2 requires click<=7.1.1,>=6.0, but you'll have click 8.0.1 which is incompatible.
pyicloud 0.10.2 requires tzlocal==2.0.0, but you'll have tzlocal 3.0 which is incompatible.
pwmled 1.6.7 requires adafruit-blinka==5.5.1, but you'll have adafruit-blinka 6.13.0 which is incompatible.
ibm-watson 5.2.2 requires websocket-client==1.1.0, but you'll have websocket-client 1.2.1 which is incompatible.
ibm-cloud-sdk-core 3.11.3 requires PyJWT<3.0.0,>=2.0.1, but you'll have pyjwt 1.7.1 which is incompatible.
hangups 0.4.14 requires protobuf<3.16,>=3.1.0, but you'll have protobuf 3.17.3 which is incompatible.
audio-metadata 0.11.1 requires attrs<19.4,>=18.2, but you'll have attrs 21.2.0 which is incompatible.
Successfully installed protobuf-3.17.3 six-1.16.0
WARNING: You are using pip version 20.2.4; however, version 21.2.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
bash-5.1# python
Python 3.9.6 (default, Jul  6 2021, 16:49:41) 
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import descriptor
>>> descriptor.__file__
'/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py'
>>> descriptor._internal_create_key
<object object at 0x7f05471fb580>
>>> 
```

But even after that I still get the same error about it not being there. Perhaps because the running instance of HA has already loaded things and has the older version cached in memory? In any case, restarting is of no use because docker images don't retain changes.

**Comment by CoryAlbrecht** [comment]
So I did a bit of digging, and I believe I have discovered that something is overwriting `/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py` in the homeassistant container when it starts up.

Using `docker create --name "tmp_$$" ghcr.io/home-assistant/qemux86-64-homeassistant:2021.9.6` then `docker export tmp_$$ | tar -tvf -` the python file shows as this:

```
-rw-r--r-- 0/0           45161 2021-09-11 16:10 usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py
```

But `docker export homeassistant | tar -tvf -` for the running container shows this:

```
-rw-r--r-- 0/0           41646 2021-09-15 12:51 usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py
```

Any ideas on how to figure out what is doing that?

**Comment by KapJI** [comment]
Ok, your pip logs show that something is downgrading protobuf to 3.6.1 which doesn't have `_internal_create_key`:
> Uninstalling protobuf-3.6.1:

That version was released in 2018: https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.1

Neither HA Core, HA OS, nor HA Supervisor do that. But probably some custom component or extension you have installed uses this old version of protobuf.

Also from your pip logs:
> hangups 0.4.14 requires protobuf<3.16,>=3.1.0, but you'll have protobuf 3.17.3 which is incompatible.

Although Protobuf 3.15.8 should satisfy this requirement. I don't think this is what causes 3.6.1 being installed but try `pip3 install --force-reinstall protobuf==3.15.8`.

**Comment by CoryAlbrecht** [comment]
@KapJI Telling me about `pipdeptree` helped me solve it. Scrolling through and searching for protobuf lead me to the integration "GTFS-RT" which I installed through HACS. Once I removed that, @leikoilja's integration here was able to start up.

The only weird thing now is that the alarms and timers `sensor.*` entities were only created for one of  the Google Mini's I have around my home. Four of them are in speaker pairs, but in that fresh VM I did that endless testing mentioned in past comments, the integration added those extra entities for the pairs. I don't know why it didn't this time, however, it would guess that it's most likely a different issue. I'll delete the integration and re add it a few times, with some rebooting to see what happens, and perhaps open another ticket.

**Thanks so much** for all your help on a problem that wasn't actually related to this item. Especially for somebody who doesn't know much (if anything) about python.

**Comment by CoryAlbrecht** [comment]
Can close thisnow.

**Comment by leikoilja** [comment]
That's some impressive problem solving here 💥 Happy it got solved. 
Awesome job for digging it out, thanks for looking so much closer at this, @KapJI 💯

**Comment by KapJI** [comment]
@CoryAlbrecht Btw, if you want to use GTFS-RT integration, you can manually import my patch while it's not merged https://github.com/zacs/ha-gtfs-rt/pull/4 (modify files in `custom_integrations` folder).

**Comment by CoryAlbrecht** [comment]
Thanks, but it's not that important right now as I am working from home. I just deleted it and will check again when I have to go back to the office regularly.
